using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CenterFlame : MonoBehaviour
{
    AudioSource myAudio;
    bool musicStart = false;

    // Start is called before the first frame update
    void Start()
    {
        myAudio = GetComponent<AudioSource>();
    }

    // Update is called once per frame
    void Update()
    {

    }



    private void OnTriggerEnter2D(Collider2D coliision)
    {
        if (coliision.CompareTag("Note"))
        {
            if (!musicStart)
            {
                myAudio.Play();
                musicStart = true;
            }

        }
    }
}
